import {
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiJson,
  SiPython,
  SiRuby,
  SiPhp,
  SiMarkdown,
  SiCplusplus,
  SiCsharp,
  SiSwift,
  SiGo,
  SiRust,
  SiKotlin,
  SiDocker,
  SiReact,
  SiAngular,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiGit,
  SiYaml,
  SiSass,
  SiC,
  SiJsonwebtokens,
  SiDotenv,
} from "react-icons/si";
import { FaJava, FaFile } from "react-icons/fa";
import { FiSettings } from "react-icons/fi";
import { BsFiletypeTxt } from "react-icons/bs";
import { BsFillImageFill } from "react-icons/bs";

export const icons = new Map([
  [".js", { icon: SiJavascript, color: "text-yellow-500" }],
  [".ts", { icon: SiTypescript, color: "text-blue-500" }],
  [".html", { icon: SiHtml5, color: "text-orange-500" }],
  [".css", { icon: SiCss3, color: "text-blue-600" }],
  [".json", { icon: SiJson, color: "text-green-500" }],
  [".py", { icon: SiPython, color: "text-blue-400" }],
  [".java", { icon: FaJava, color: "text-red-600" }],
  [".rb", { icon: SiRuby, color: "text-red-500" }],
  [".php", { icon: SiPhp, color: "text-purple-700" }],
  [".md", { icon: SiMarkdown, color: "text-gray-600" }],
  [".cpp", { icon: SiCplusplus, color: "text-blue-500" }],
  [".cs", { icon: SiCsharp, color: "text-green-700" }],
  [".swift", { icon: SiSwift, color: "text-orange-400" }],
  [".go", { icon: SiGo, color: "text-blue-500" }],
  [".rs", { icon: SiRust, color: "text-orange-600" }],
  [".kt", { icon: SiKotlin, color: "text-purple-600" }],
  [".dockerfile", { icon: SiDocker, color: "text-blue-500" }],
  [".jsx", { icon: SiReact, color: "text-blue-400" }],
  [".tsx", { icon: SiReact, color: "text-blue-300" }],
  [".angular", { icon: SiAngular, color: "text-red-600" }],
  [".mongo", { icon: SiMongodb, color: "text-green-600" }],
  [".sql", { icon: SiMysql, color: "text-blue-500" }],
  [".pgsql", { icon: SiPostgresql, color: "text-blue-700" }],
  [".gitignore", { icon: SiGit, color: "text-red-600" }],
  [".yml", { icon: SiYaml, color: "text-blue-700" }],
  [".scss", { icon: SiSass, color: "text-pink-500" }],
  [".env", { icon: SiDotenv, color: "text-green-500" }],
  [".config", { icon: FiSettings, color: "text-gray-700" }],
  [".toml", { icon: FiSettings, color: "text-gray-600" }],
  [".c", { icon: SiC, color: "text-blue-600" }],
  [".jwt", { icon: SiJsonwebtokens, color: "text-green-500" }],
  [".txt", { icon: BsFiletypeTxt, color: "text-blue-500" }],
  ["default", { icon: FaFile, color: "text-yellow-700" }],
  [".png", { icon: BsFillImageFill, color: "text-green-700" }],
  [".jpg", { icon: BsFillImageFill, color: "text-green-500" }],
  [".jpeg", { icon: BsFillImageFill, color: "text-green-700" }],
  [".webp", { icon: BsFillImageFill, color: "text-green-500" }],
]);
